apiVersion: v1
kind: Service
metadata:
  name: pnl-postgres
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app.kubernetes.io/name: pnl-postgres

