apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flamres
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: flamres-values
    files:
      - values.yaml=values.yaml
resources:
  - namespace.yaml
  - pvc.yaml
  - helmrelease.yaml
