cloudflare-tunnel:
  enabled: true
  cloudflare:
    enableWarp: false
    ingress:
      - hostname: books.koohyom.in
        path: '^/ngsw\.json$'
        service: http_status:404
      - hostname: "*.koohyom.in"
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
    secretName: cloudflare-tunnel-credentials
    tunnelId: 9b1820c5-3168-4638-a1f0-9fe1585eda94
    tunnelName: colima-k8s-koohyomin
  image:
    tag: "2026.2.0"
  replicaCount: 2
