apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triflam-bot-opencode-data
  namespace: triflam-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triflam-bot-workdir
  namespace: triflam-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
  volumeMode: Filesystem
