apiVersion: v1
kind: Service
metadata:
  name: triflam-bot
  namespace: triflam-bot
spec:
  type: ClusterIP
  selector:
    app: triflam-bot
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
