apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - sources/helmrepositories.yaml
  - controllers/ingress-nginx
  - controllers/cloudflare-tunnel
  - controllers/external-dns
