apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sake-api
  namespace: sake
spec:
  interval: 10m0s
  releaseName: sake-api
  targetNamespace: sake
  dependsOn:
    - name: sake-deps
  chart:
    spec:
      chart: ./charts/sake-api
      interval: 10m0s
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: sake-api-values
      valuesKey: values.yaml
