apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sake
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: sake-deps-values
    files:
      - values.yaml=deps-values.yaml
  - name: sake-api-values
    files:
      - values.yaml=api-values.yaml
  - name: sake-worker-values
    files:
      - values.yaml=worker-values.yaml
resources:
  - namespace.yaml
  - helmrelease-deps.yaml
  - helmrelease-api.yaml
  - helmrelease-worker.yaml
