namespace: sake
image:
  repository: ghcr.io/triflam/sake-studio
  tag: main-bf1c8bb
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-auth
secretRefs:
  - name: sake-dev-secrets
    optional: false
ingress:
  enabled: true
  className: nginx
  host: studio-sake.koohyom.in
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/target: 9b1820c5-3168-4638-a1f0-9fe1585eda94.cfargotunnel.com
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: sake-studio-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
