apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sake-worker.fullname" . }}
  namespace: {{ include "sake-worker.namespace" . }}
  labels:
    {{- include "sake-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sake-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sake-worker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ required "sake-worker image.tag is required" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ with .Values.container.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{ end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ .Values.configMap.name }}
            {{- end }}
            {{- range .Values.secretRefs }}
            - secretRef:
                name: {{ .name }}
                optional: {{ default false .optional }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
