apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: insights-write
  namespace: koohyomin
spec:
  interval: 10m0s
  releaseName: insights-write
  targetNamespace: koohyomin
  chart:
    spec:
      chart: ./charts/insights-write
      interval: 10m0s
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: insights-write-values
      valuesKey: values.yaml
