{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ include "flamres.namespace" . }}
  labels:
    {{- include "flamres.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.config }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
