apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ns2-alert-bot.fullname" . }}
  namespace: {{ include "ns2-alert-bot.namespace" . }}
  labels:
    {{- include "ns2-alert-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ns2-alert-bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ns2-alert-bot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ required "ns2-alert-bot image.tag is required" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.container.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ .Values.configMap.name }}
            {{- end }}
            {{- range .Values.secretRefs }}
            - secretRef:
                name: {{ .name }}
                optional: {{ default false .optional }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}
      {{- end }}
