apiVersion: v1
kind: ConfigMap
metadata:
  name: pnl-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

