{{- if .Values.cloudflareTunnelCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflareTunnelCredentials.name }}
  namespace: {{ .Values.cloudflareTunnelCredentials.namespace }}
  labels:
    {{- include "cloudflare-kube-tunnel.labels" . | nindent 4 }}
type: Opaque
stringData:
  credentials.json: |-
{{ .Values.cloudflareTunnelCredentials.credentialsJson | required "cloudflareTunnelCredentials.credentialsJson is required when cloudflareTunnelCredentials.create=true" | nindent 4 }}
{{- end }}
