{{- if .Values.externalDnsToken.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalDnsToken.name }}
  namespace: {{ .Values.externalDnsToken.namespace }}
  labels:
    {{- include "cloudflare-kube-tunnel.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.externalDnsToken.apiToken | required "externalDnsToken.apiToken is required when externalDnsToken.create=true" | quote }}
{{- end }}
