apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ include "sake-deps.namespace" . }}
  labels:
    {{- include "sake-deps.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "sake-deps.appName" . }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.postgres.username .Values.secret.postgresPassword (include "sake-deps.postgresName" .) .Values.postgres.service.port .Values.postgres.database | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secret.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secret.minioSecretKey | quote }}
  OBJECT_STORE_ACCESS_KEY_ID: {{ .Values.secret.minioAccessKey | quote }}
  OBJECT_STORE_SECRET_ACCESS_KEY: {{ .Values.secret.minioSecretKey | quote }}
