namespace: koohyomin
image:
  repository: ghcr.io/eatsteak/ns2-alert-bot
  tag: main-07e83f6273f314b1bd07fd9a901fbd31b1efbdd2
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-auth
container:
  command:
    - ns2-alert-bot
    - --config
    - /app/config/targets.yaml
    - run
config:
  POLL_INTERVAL_SECONDS: "60"
  STATE_DB_PATH: /data/ns2-alert-bot.sqlite3
  HTTP_TIMEOUT_SECONDS: "15"
