namespace: ns2-alert-bot
image:
  repository: ghcr.io/eatsteak/ns2-alert-bot
  tag: main-9105b0c6591153a312ae645dda6478955a9d67c6
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-auth
config:
  POLL_INTERVAL_SECONDS: "60"
  STATE_DB_PATH: /data/ns2-alert-bot.sqlite3
  HTTP_TIMEOUT_SECONDS: "15"
