apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: canvas
  namespace: koohyomin
spec:
  interval: 10m0s
  releaseName: canvas
  targetNamespace: koohyomin
  chart:
    spec:
      chart: ./charts/canvas
      interval: 10m0s
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: canvas-values
      valuesKey: values.yaml
