apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: koohyomin
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: canvas-values
    files:
      - values.yaml=values.yaml
resources:
  - pvc.yaml
  - helmrelease.yaml
