apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canvas-data
  namespace: koohyomin
  labels:
    app: canvas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
