apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pnl-deps
  namespace: pnl
spec:
  interval: 10m0s
  releaseName: pnl-deps
  targetNamespace: pnl
  chart:
    spec:
      chart: ./charts/pnl-deps
      interval: 10m0s
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: pnl-deps-values
      valuesKey: values.yaml

