apiVersion: v2
name: cloudflare-kube-tunnel
description: Deploy Cloudflare Tunnel for an existing Kubernetes ingress controller.
type: application
version: 0.2.0
appVersion: "0.2.0"
home: https://github.com/EATSTEAK/local-helm
sources:
  - https://github.com/cloudflare/helm-charts
keywords:
  - cloudflare
  - cloudflared
  - tunnel
  - colima
  - kubernetes
  - ingress
  - existing-controller
dependencies:
  - name: cloudflare-tunnel
    version: 0.3.2
    repository: https://cloudflare.github.io/helm-charts
    condition: cloudflare-tunnel.enabled
